# 머신러닝 강좌 4번째 : 다변량 선형회귀분석

In [11]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
#tf.set_random_seed(777)  # for reproducibility 

#아래부분을 matrix로 바꿀것 : 다음 셀 참조
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
#print(hypothesis)

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 50 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
'''
sess.run(train)할때마다 minimize함수가 사용되면서 미분이 실행되고 cost가 떨어지게 된다. 
'''        

        
# cost값이 실행할때 변동된다        


0 Cost:  940.553 
Prediction:
 [ 132.19496155  147.32862854  150.86448669  167.0267334   107.31474304]
50 Cost:  42.685 
Prediction:
 [ 158.64736938  179.34814453  182.29681396  201.2640686   131.78686523]
100 Cost:  41.6469 
Prediction:
 [ 158.52966309  179.42930603  182.2613678   201.2335968   131.8974762 ]
150 Cost:  40.6364 
Prediction:
 [ 158.41357422  179.50938416  182.22642517  201.20349121  132.00660706]
200 Cost:  39.6526 
Prediction:
 [ 158.29907227  179.58833313  182.19195557  201.17372131  132.11431885]
250 Cost:  38.6949 
Prediction:
 [ 158.18615723  179.66625977  182.1579895   201.14434814  132.22062683]
300 Cost:  37.7626 
Prediction:
 [ 158.07478333  179.74308777  182.12446594  201.11528015  132.32551575]
350 Cost:  36.8551 
Prediction:
 [ 157.9649353   179.81887817  182.09144592  201.08657837  132.42901611]
400 Cost:  35.9715 
Prediction:
 [ 157.85658264  179.89363098  182.05885315  201.05821228  132.53117371]
450 Cost:  35.1114 
Prediction:
 [ 157.74972534  179.967376

'\n0 Cost:  19614.8\nPrediction:\n [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]\n10 Cost:  14.0682\nPrediction:\n [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]\n\n ...\n\n1990 Cost:  4.9197\nPrediction:\n [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]\n2000 Cost:  4.89449\nPrediction:\n [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]\n'

In [12]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) #none : 데이터 shape에 따라 자동지정
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  15437.7 
Prediction:
 [[ 262.0916748 ]
 [ 316.49237061]
 [ 310.7432251 ]
 [ 341.7947998 ]
 [ 239.09855652]]
10 Cost:  6.11477 
Prediction:
 [[ 152.1955719 ]
 [ 184.41523743]
 [ 180.60035706]
 [ 200.07208252]
 [ 138.35975647]]
20 Cost:  5.9607 
Prediction:
 [[ 151.85797119]
 [ 184.01921082]
 [ 180.20515442]
 [ 199.64131165]
 [ 138.06044006]]
30 Cost:  5.94792 
Prediction:
 [[ 151.85185242]
 [ 184.02159119]
 [ 180.20249939]
 [ 199.63803101]
 [ 138.0650177 ]]
40 Cost:  5.93526 
Prediction:
 [[ 151.84677124]
 [ 184.02516174]
 [ 180.20106506]
 [ 199.63606262]
 [ 138.07048035]]
50 Cost:  5.92258 
Prediction:
 [[ 151.84170532]
 [ 184.0287323 ]
 [ 180.19961548]
 [ 199.63407898]
 [ 138.07595825]]
60 Cost:  5.91003 
Prediction:
 [[ 151.83665466]
 [ 184.0322876 ]
 [ 180.19821167]
 [ 199.63214111]
 [ 138.0814209 ]]
70 Cost:  5.89753 
Prediction:
 [[ 151.83161926]
 [ 184.0358429 ]
 [ 180.1967926 ]
 [ 199.63018799]
 [ 138.08685303]]
80 Cost:  5.88503 
Prediction:
 [[ 151.8265686 ]
 [ 184.03

700 Cost:  5.21501 
Prediction:
 [[ 151.542099  ]
 [ 184.24017334]
 [ 180.11553955]
 [ 199.51333618]
 [ 138.40400696]]
710 Cost:  5.20569 
Prediction:
 [[ 151.53793335]
 [ 184.24313354]
 [ 180.11437988]
 [ 199.51159668]
 [ 138.40866089]]
720 Cost:  5.1964 
Prediction:
 [[ 151.53375244]
 [ 184.24607849]
 [ 180.11322021]
 [ 199.50984192]
 [ 138.41329956]]
730 Cost:  5.18713 
Prediction:
 [[ 151.52960205]
 [ 184.24902344]
 [ 180.11207581]
 [ 199.50808716]
 [ 138.41793823]]
740 Cost:  5.17792 
Prediction:
 [[ 151.52546692]
 [ 184.25195312]
 [ 180.11091614]
 [ 199.50634766]
 [ 138.42256165]]
750 Cost:  5.16875 
Prediction:
 [[ 151.52134705]
 [ 184.25488281]
 [ 180.10978699]
 [ 199.50460815]
 [ 138.4271698 ]]
760 Cost:  5.15965 
Prediction:
 [[ 151.51722717]
 [ 184.25779724]
 [ 180.10864258]
 [ 199.50286865]
 [ 138.43174744]]
770 Cost:  5.15056 
Prediction:
 [[ 151.5131073 ]
 [ 184.26068115]
 [ 180.10748291]
 [ 199.50111389]
 [ 138.43632507]]
780 Cost:  5.14151 
Prediction:
 [[ 151.5090332 ]

1410 Cost:  4.64447 
Prediction:
 [[ 151.27438354]
 [ 184.4302063 ]
 [ 180.04179382]
 [ 199.39562988]
 [ 138.7077179 ]]
1420 Cost:  4.63761 
Prediction:
 [[ 151.27101135]
 [ 184.43261719]
 [ 180.04089355]
 [ 199.39407349]
 [ 138.7116394 ]]
1430 Cost:  4.63077 
Prediction:
 [[ 151.26765442]
 [ 184.43501282]
 [ 180.03997803]
 [ 199.39251709]
 [ 138.71556091]]
1440 Cost:  4.62396 
Prediction:
 [[ 151.26428223]
 [ 184.43740845]
 [ 180.0390625 ]
 [ 199.39094543]
 [ 138.7194519 ]]
1450 Cost:  4.61717 
Prediction:
 [[ 151.26092529]
 [ 184.43978882]
 [ 180.03813171]
 [ 199.38937378]
 [ 138.7233429 ]]
1460 Cost:  4.61045 
Prediction:
 [[ 151.25758362]
 [ 184.44216919]
 [ 180.03723145]
 [ 199.38783264]
 [ 138.72721863]]
1470 Cost:  4.60371 
Prediction:
 [[ 151.2542572 ]
 [ 184.44456482]
 [ 180.03633118]
 [ 199.38627625]
 [ 138.73109436]]
1480 Cost:  4.59704 
Prediction:
 [[ 151.25094604]
 [ 184.44691467]
 [ 180.03543091]
 [ 199.38473511]
 [ 138.73495483]]
1490 Cost:  4.5904 
Prediction:
 [[ 151.