Numpy : #같은 폴더에 넣으니 된다. path지정을 안해줘 된다면,,,불러오는 곳이 정해져 있다는 것인가?
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32) 

tensorflow에서도 파일 불러올 수 있네(마지막 cell 참조)

*파일 위치바꿔서 다시 불러와보자

In [6]:
#slicing 기능이 있다
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32) #같은 폴더에 넣으니 된다.
x_data = xy[:, 0:-1] #from a to b 에서 b는 포함하지 않는다.
y_data = xy[:, [-1]] #마지막 컬럼을 -1이라고 한다

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data)) #행 by 열, 데이터, 행의 수
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight') # 3 by 1의 매트릭스를 만든다.
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

# new test score
print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]

'''


(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
0 Cost:  181274.0 
Prediction:
 [[-241.4982605 ]
 [-300.36126709]
 [-290.77703857]
 [-316.65661621]
 [-231.53591919]
 [-171.71369934]
 [-234.05566406]
 [-169.09115601]
 [-282.95507812]
 [-262.84765625]
 [-228.53399658]
 [-229.745

180 Cost:  24.8574 
Prediction:
 [[ 158.4045105 ]
 [ 180.97291565]
 [ 183.12518311]
 [ 199.57714844]
 [ 135.63311768]
 [  99.2477951 ]
 [ 152.34609985]
 [ 117.31916046]
 [ 167.19000244]
 [ 154.41903687]
 [ 143.82771301]
 [ 137.76034546]
 [ 188.83712769]
 [ 156.15126038]
 [ 151.66690063]
 [ 184.66760254]
 [ 145.61798096]
 [ 185.04330444]
 [ 181.45672607]
 [ 163.43728638]
 [ 177.19277954]
 [ 170.56329346]
 [ 169.69767761]
 [ 158.97137451]
 [ 188.9291687 ]]
190 Cost:  24.7101 
Prediction:
 [[ 158.38378906]
 [ 180.98480225]
 [ 183.11743164]
 [ 199.57498169]
 [ 135.64611816]
 [  99.27137756]
 [ 152.34350586]
 [ 117.31478119]
 [ 167.21733093]
 [ 154.46151733]
 [ 143.82971191]
 [ 137.78097534]
 [ 188.823349  ]
 [ 156.13328552]
 [ 151.67050171]
 [ 184.68225098]
 [ 145.60464478]
 [ 185.03564453]
 [ 181.43690491]
 [ 163.41671753]
 [ 177.19281006]
 [ 170.57821655]
 [ 169.69277954]
 [ 158.93682861]
 [ 188.93276978]]
200 Cost:  24.564 
Prediction:
 [[ 158.3631134 ]
 [ 180.99659729]
 [ 183.1096344 ]

420 Cost:  21.6364 
Prediction:
 [[ 157.92919922]
 [ 181.24621582]
 [ 182.9475708 ]
 [ 199.52651978]
 [ 135.93356323]
 [  99.78805542]
 [ 152.28330994]
 [ 117.21289825]
 [ 167.81565857]
 [ 155.38949585]
 [ 143.87239075]
 [ 138.23173523]
 [ 188.52276611]
 [ 155.74299622]
 [ 151.74575806]
 [ 185.00283813]
 [ 145.31806946]
 [ 184.86236572]
 [ 181.00424194]
 [ 162.96685791]
 [ 177.18969727]
 [ 170.90475464]
 [ 169.58247375]
 [ 158.18258667]
 [ 189.01286316]]
430 Cost:  21.5155 
Prediction:
 [[ 157.91035461]
 [ 181.25708008]
 [ 182.9405365 ]
 [ 199.52445984]
 [ 135.94554138]
 [  99.80944061]
 [ 152.28065491]
 [ 117.20841217]
 [ 167.84040833]
 [ 155.42776489]
 [ 143.87408447]
 [ 138.25035095]
 [ 188.51039124]
 [ 155.727005  ]
 [ 151.74873352]
 [ 185.01609802]
 [ 145.30644226]
 [ 184.85496521]
 [ 180.98640442]
 [ 162.94827271]
 [ 177.18940735]
 [ 170.91825867]
 [ 169.57777405]
 [ 158.151474  ]
 [ 189.01623535]]
440 Cost:  21.3957 
Prediction:
 [[ 157.89163208]
 [ 181.26794434]
 [ 182.93357849

690 Cost:  18.6968 
Prediction:
 [[ 157.44656372]
 [ 181.52694702]
 [ 182.76899719]
 [ 199.47363281]
 [ 136.24468994]
 [ 100.33620453]
 [ 152.21246338]
 [ 117.09127045]
 [ 168.45053101]
 [ 156.36727905]
 [ 143.91539001]
 [ 138.70817566]
 [ 188.2089386 ]
 [ 155.33804321]
 [ 151.81881714]
 [ 185.3429718 ]
 [ 145.02783203]
 [ 184.66725159]
 [ 180.55001831]
 [ 162.49285889]
 [ 177.17993164]
 [ 171.25097656]
 [ 169.45986938]
 [ 157.3898468 ]
 [ 189.10227966]]
700 Cost:  18.5999 
Prediction:
 [[ 157.42967224]
 [ 181.53683472]
 [ 182.76278687]
 [ 199.47174072]
 [ 136.25569153]
 [ 100.35539246]
 [ 152.20985413]
 [ 117.08674622]
 [ 168.47276306]
 [ 156.40135193]
 [ 143.9168396 ]
 [ 138.72480774]
 [ 188.19807434]
 [ 155.32406616]
 [ 151.82124329]
 [ 185.35487366]
 [ 145.01794434]
 [ 184.66020203]
 [ 180.53422546]
 [ 162.47633362]
 [ 177.17945862]
 [ 171.26307678]
 [ 169.45545959]
 [ 157.36225891]
 [ 189.10549927]]
710 Cost:  18.5038 
Prediction:
 [[ 157.4128418 ]
 [ 181.54667664]
 [ 182.7565918 

970 Cost:  16.2608 
Prediction:
 [[ 156.99822998]
 [ 181.79104614]
 [ 182.60498047]
 [ 199.42300415]
 [ 136.53993225]
 [ 100.84494781]
 [ 152.13934326]
 [ 116.9641571 ]
 [ 169.03985596]
 [ 157.26763916]
 [ 143.95289612]
 [ 139.1484375 ]
 [ 187.92303467]
 [ 154.97180176]
 [ 151.87945557]
 [ 185.65861511]
 [ 144.77296448]
 [ 184.47424316]
 [ 180.13345337]
 [ 162.05636597]
 [ 177.16403198]
 [ 171.57202148]
 [ 169.3401947 ]
 [ 156.66197205]
 [ 189.18994141]]
980 Cost:  16.1836 
Prediction:
 [[ 156.98312378]
 [ 181.80001831]
 [ 182.59950256]
 [ 199.42129517]
 [ 136.55001831]
 [ 100.86206818]
 [ 152.13677979]
 [ 116.95960999]
 [ 169.0597229 ]
 [ 157.29785156]
 [ 143.95413208]
 [ 139.16325378]
 [ 187.91351318]
 [ 154.95965576]
 [ 151.88137817]
 [ 185.66925049]
 [ 144.76467896]
 [ 184.4675293 ]
 [ 180.11953735]
 [ 162.04174805]
 [ 177.16337585]
 [ 171.58283997]
 [ 169.33609009]
 [ 156.63763428]
 [ 189.19299316]]
990 Cost:  16.1071 
Prediction:
 [[ 156.96809387]
 [ 181.8089447 ]
 [ 182.59405518

 [ 189.26983643]]
1250 Cost:  14.3189 
Prediction:
 [[ 156.59727478]
 [ 182.03039551]
 [ 182.46006775]
 [ 199.37638855]
 [ 136.80989075]
 [ 101.2995224 ]
 [ 152.06713867]
 [ 116.83720398]
 [ 169.56654358]
 [ 158.06552124]
 [ 143.98417664]
 [ 139.54011536]
 [ 187.67262268]
 [ 154.65357971]
 [ 151.92692566]
 [ 185.94068909]
 [ 144.55891418]
 [ 184.29063416]
 [ 179.76597595]
 [ 161.66958618]
 [ 177.14344788]
 [ 171.85868835]
 [ 169.22776794]
 [ 156.01899719]
 [ 189.27268982]]
1260 Cost:  14.2573 
Prediction:
 [[ 156.58377075]
 [ 182.03851318]
 [ 182.45523071]
 [ 199.37478638]
 [ 136.8190918 ]
 [ 101.31483459]
 [ 152.0645752 ]
 [ 116.83267975]
 [ 169.58428955]
 [ 158.09228516]
 [ 143.98519897]
 [ 139.55325317]
 [ 187.66424561]
 [ 154.64300537]
 [ 151.92840576]
 [ 185.95018005]
 [ 144.55194092]
 [ 184.28427124]
 [ 179.75367737]
 [ 161.65661621]
 [ 177.1426239 ]
 [ 171.86834717]
 [ 169.22387695]
 [ 155.99746704]
 [ 189.27554321]]
1270 Cost:  14.1961 
Prediction:
 [[ 156.57032776]
 [ 182.0466

1490 Cost:  12.9686 
Prediction:
 [[ 156.28735352]
 [ 182.21772766]
 [ 182.34934998]
 [ 199.33930969]
 [ 137.0229187 ]
 [ 101.65060425]
 [ 152.0062561 ]
 [ 116.72924805]
 [ 169.97338867]
 [ 158.67681885]
 [ 144.00668335]
 [ 139.84127808]
 [ 187.48291016]
 [ 154.41445923]
 [ 151.95861816]
 [ 186.15852356]
 [ 144.40365601]
 [ 184.14056396]
 [ 179.48565674]
 [ 161.3732605 ]
 [ 177.12280273]
 [ 172.07992554]
 [ 169.13687134]
 [ 155.52786255]
 [ 189.33984375]]
1500 Cost:  12.9178 
Prediction:
 [[ 156.27507019]
 [ 182.22520447]
 [ 182.34498596]
 [ 199.33782959]
 [ 137.03144836]
 [ 101.66452026]
 [ 152.00375366]
 [ 116.72478485]
 [ 169.98951721]
 [ 158.70095825]
 [ 144.0075531 ]
 [ 139.85317993]
 [ 187.47547913]
 [ 154.40512085]
 [ 151.95976257]
 [ 186.16716003]
 [ 144.39772034]
 [ 184.13447571]
 [ 179.47462463]
 [ 161.36155701]
 [ 177.12188721]
 [ 172.08869934]
 [ 169.13319397]
 [ 155.50852966]
 [ 189.34257507]]
1510 Cost:  12.8673 
Prediction:
 [[ 156.26281738]
 [ 182.23265076]
 [ 182.34063

1730 Cost:  11.8532 
Prediction:
 [[ 156.00546265]
 [ 182.39012146]
 [ 182.24978638]
 [ 199.30473328]
 [ 137.22039795]
 [ 101.96966553]
 [ 151.94656372]
 [ 116.62265778]
 [ 170.34320068]
 [ 159.22816467]
 [ 144.02572632]
 [ 140.11386108]
 [ 187.31375122]
 [ 154.20291138]
 [ 151.9831543 ]
 [ 186.35652161]
 [ 144.27127075]
 [ 183.99713135]
 [ 179.23391724]
 [ 161.10601807]
 [ 177.09997559]
 [ 172.28085327]
 [ 169.05076599]
 [ 155.08624268]
 [ 189.40368652]]
1740 Cost:  11.8111 
Prediction:
 [[ 155.99429321]
 [ 182.39700317]
 [ 182.24586487]
 [ 199.30334473]
 [ 137.22831726]
 [ 101.98230743]
 [ 151.94410706]
 [ 116.61824799]
 [ 170.35786438]
 [ 159.24992371]
 [ 144.02645874]
 [ 140.12464905]
 [ 187.30711365]
 [ 154.19462585]
 [ 151.98402405]
 [ 186.36436462]
 [ 144.26618958]
 [ 183.99128723]
 [ 179.22399902]
 [ 161.09547424]
 [ 177.09898376]
 [ 172.2888031 ]
 [ 169.04728699]
 [ 155.0688324 ]
 [ 189.40629578]]
1750 Cost:  11.7694 
Prediction:
 [[ 155.9831543 ]
 [ 182.40383911]
 [ 182.24192

Other scores will be  [[ 181.15431213]
 [ 180.54098511]]


'\nYour score will be  [[ 181.73277283]]\nOther scores will be  [[ 145.86265564]\n [ 187.23129272]]\n\n'

In [5]:

import tensorflow as tf
#tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['../data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]  # 리스트형태의 메모리 각 마디마다 자료형태 정하기
xy = tf.decode_csv(value, record_defaults=record_defaults) #각 마디 저장소로부터 value값을 가져와 xy에 넣기

print(xy)
# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
print(train_x_batch)


[<tf.Tensor 'DecodeCSV_3:0' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_3:1' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_3:2' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_3:3' shape=() dtype=float32>]
Tensor("batch_3:0", shape=(10, 3), dtype=float32)


In [2]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    #batch가 10개씩 추출이면...for문 돌리는게 맞다
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


0 Cost:  168151.0 
Prediction:
 [[-227.18965149]
 [-293.4274292 ]
 [-278.17980957]
 [-307.73580933]
 [-225.02133179]
 [-175.87539673]
 [-231.91377258]
 [-173.45648193]
 [-284.90740967]
 [-276.42721558]]
10 Cost:  224.762 
Prediction:
 [[ 162.70359802]
 [ 175.35903931]
 [ 183.63154602]
 [ 195.25517273]
 [ 132.51142883]
 [  87.80579376]
 [ 144.60913086]
 [ 105.69280243]
 [ 153.29951477]
 [ 129.57002258]]
20 Cost:  184.99 
Prediction:
 [[ 165.2807312 ]
 [ 178.55189514]
 [ 186.72610474]
 [ 198.65322876]
 [ 134.94721985]
 [  89.65576172]
 [ 147.16740417]
 [ 107.60709381]
 [ 156.33969116]
 [ 132.45614624]]
30 Cost:  183.1 
Prediction:
 [[ 165.24440002]
 [ 178.60269165]
 [ 186.72520447]
 [ 198.67990112]
 [ 134.98661804]
 [  89.73854065]
 [ 147.20201111]
 [ 107.65041351]
 [ 156.44287109]
 [ 132.62132263]]
40 Cost:  181.429 
Prediction:
 [[ 165.19067383]
 [ 178.63214111]
 [ 186.70352173]
 [ 198.68380737]
 [ 135.00973511]
 [  89.80905151]
 [ 147.21948242]
 [ 107.68095398]
 [ 156.52584839]
 [ 132

500 Cost:  119.201 
Prediction:
 [[ 162.96141052]
 [ 179.84599304]
 [ 185.79971313]
 [ 198.83889771]
 [ 135.96307373]
 [  92.72502899]
 [ 147.93765259]
 [ 108.93984222]
 [ 159.95555115]
 [ 138.81097412]]
510 Cost:  118.121 
Prediction:
 [[ 162.91793823]
 [ 179.86964417]
 [ 185.78210449]
 [ 198.84191895]
 [ 135.98167419]
 [  92.78186798]
 [ 147.95162964]
 [ 108.96435547]
 [ 160.0223999 ]
 [ 138.9287262 ]]
520 Cost:  117.052 
Prediction:
 [[ 162.87469482]
 [ 179.89321899]
 [ 185.76457214]
 [ 198.84492493]
 [ 136.00018311]
 [  92.83844757]
 [ 147.96554565]
 [ 108.98872375]
 [ 160.088974  ]
 [ 139.04600525]]
530 Cost:  115.992 
Prediction:
 [[ 162.83161926]
 [ 179.91667175]
 [ 185.74711609]
 [ 198.84791565]
 [ 136.01863098]
 [  92.89477539]
 [ 147.97938538]
 [ 109.01300049]
 [ 160.1552124 ]
 [ 139.16270447]]
540 Cost:  114.942 
Prediction:
 [[ 162.78875732]
 [ 179.9400177 ]
 [ 185.72973633]
 [ 198.85090637]
 [ 136.0369873 ]
 [  92.95084381]
 [ 147.99317932]
 [ 109.03717804]
 [ 160.22116089

940 Cost:  80.0351 
Prediction:
 [[ 161.22496033]
 [ 180.79214478]
 [ 185.09611511]
 [ 198.95936584]
 [ 136.70697021]
 [  94.99614716]
 [ 148.49536133]
 [ 109.91726685]
 [ 162.62687683]
 [ 143.51655579]]
950 Cost:  79.3182 
Prediction:
 [[ 161.18940735]
 [ 180.81155396]
 [ 185.08171082]
 [ 198.96182251]
 [ 136.72221375]
 [  95.04264069]
 [ 148.50679016]
 [ 109.93723297]
 [ 162.68156433]
 [ 143.61289978]]
960 Cost:  78.608 
Prediction:
 [[ 161.15400696]
 [ 180.83082581]
 [ 185.06736755]
 [ 198.96427917]
 [ 136.73738098]
 [  95.08894348]
 [ 148.51811218]
 [ 109.95711517]
 [ 162.73600769]
 [ 143.70878601]]
970 Cost:  77.9044 
Prediction:
 [[ 161.11877441]
 [ 180.85003662]
 [ 185.05311584]
 [ 198.96672058]
 [ 136.75250244]
 [  95.13502502]
 [ 148.52941895]
 [ 109.97692108]
 [ 162.79022217]
 [ 143.804245  ]]
980 Cost:  77.2074 
Prediction:
 [[ 161.0836792 ]
 [ 180.86914062]
 [ 185.03889465]
 [ 198.96914673]
 [ 136.76753235]
 [  95.18088531]
 [ 148.54064941]
 [ 109.99662018]
 [ 162.84416199]

1350 Cost:  55.4999 
Prediction:
 [[ 159.89225769]
 [ 181.51887512]
 [ 184.55644226]
 [ 199.05155945]
 [ 137.27893066]
 [  96.73905182]
 [ 148.92211914]
 [ 110.6648941 ]
 [ 164.67695618]
 [ 147.12660217]]
1360 Cost:  55.0112 
Prediction:
 [[ 159.86276245]
 [ 181.53495789]
 [ 184.54447937]
 [ 199.05357361]
 [ 137.29159546]
 [  96.77761841]
 [ 148.93154907]
 [ 110.68140411]
 [ 164.7223053 ]
 [ 147.20646667]]
1370 Cost:  54.527 
Prediction:
 [[ 159.83340454]
 [ 181.55101013]
 [ 184.53262329]
 [ 199.05563354]
 [ 137.30422974]
 [  96.81601715]
 [ 148.94093323]
 [ 110.69784546]
 [ 164.76748657]
 [ 147.28598022]]
1380 Cost:  54.0473 
Prediction:
 [[ 159.80418396]
 [ 181.56695557]
 [ 184.52078247]
 [ 199.05763245]
 [ 137.31677246]
 [  96.85422516]
 [ 148.95027161]
 [ 110.71421051]
 [ 164.81243896]
 [ 147.36514282]]
1390 Cost:  53.5721 
Prediction:
 [[ 159.77507019]
 [ 181.58280945]
 [ 184.50900269]
 [ 199.05964661]
 [ 137.32926941]
 [  96.89227295]
 [ 148.95956421]
 [ 110.73049927]
 [ 164.8571

1770 Cost:  38.4532 
Prediction:
 [[ 158.76226807]
 [ 182.13555908]
 [ 184.09913635]
 [ 199.12947083]
 [ 137.76481628]
 [  98.21665955]
 [ 149.28276062]
 [ 111.29650879]
 [ 166.41506958]
 [ 150.18617249]]
1780 Cost:  38.1237 
Prediction:
 [[ 158.73791504]
 [ 182.14886475]
 [ 184.08927917]
 [ 199.13114929]
 [ 137.77531433]
 [  98.2485199 ]
 [ 149.29052734]
 [ 111.31010437]
 [ 166.45251465]
 [ 150.25210571]]
1790 Cost:  37.7973 
Prediction:
 [[ 158.71366882]
 [ 182.16210938]
 [ 184.07946777]
 [ 199.13282776]
 [ 137.78575134]
 [  98.2802124 ]
 [ 149.29824829]
 [ 111.32361603]
 [ 166.48980713]
 [ 150.31773376]]
1800 Cost:  37.474 
Prediction:
 [[ 158.68952942]
 [ 182.17526245]
 [ 184.06968689]
 [ 199.13447571]
 [ 137.79612732]
 [  98.31177521]
 [ 149.30592346]
 [ 111.33708191]
 [ 166.52693176]
 [ 150.38305664]]
1810 Cost:  37.1537 
Prediction:
 [[ 158.66549683]
 [ 182.18840027]
 [ 184.05996704]
 [ 199.13612366]
 [ 137.80648804]
 [  98.3431778 ]
 [ 149.31358337]
 [ 111.35047913]
 [ 166.5638